### ISSUE TITLE
lui.legacy.js benutzt

### ISSUE THREAD

**Issue by L3P3** [LFF5644/XOX#2]
Da die app.js in neuerem Format ist mit z. B. Pfeilfunktionen, bringt es gar nichts, die legacy-Variante von lui zu benutzen. Also nur Platzverschwendung.
Bitte durch lui.js ersetzen und erst später lui.legacy.js benutzen wenn app.js auch im älteren Format ist.

**Comment by LFF5644** [comment]
[gefixt](https://github.com/LFF5644/XOX/commit/ae33378b64c8f84fb569c793baf9da3a8598a477)
