### ISSUE TITLE
GitHub-Aktion aufräumen und API fixen

### ISSUE THREAD

**Issue by L3P3** [LFF5644/XOX#3]
Wenn das Repo verändert wird, werden 3 unnötige Schritte ausgeführt:
- Checkout
- Setting up NodeJS
- Install closure compiler

Die armen GitHub-Server tun all das obwohl (noch) garnichts kompiliert wird, sondern es wird nur curl ausgeführt.

Und curl gibt zurück dass es einen Server-seitigen Fehler gibt.

**Comment by LFF5644** [comment]
ja das wird noch gefixt
